package media

import (
	"fmt"
	"strings"
)

// MediaMTXConfig holds the structured representation of a MediaMTX configuration.
// This is used to generate YAML config for the MediaMTX process.
//
// Design constraints:
//   - No transcoding directives (no ffmpeg, no runOnReady scripts)
//   - No recording directives
//   - Codec passthrough only (readRT)
//   - WebRTC enabled (preferred output), HLS as fallback
//   - On-demand connection enabled
//   - Maximum 4 stream paths
//   - Source URL uses placeholder - actual credentials from encrypted config
type MediaMTXConfig struct {
	streams []StreamConfig
}

// NewMediaMTXConfig creates a new MediaMTX configuration generator.
func NewMediaMTXConfig() *MediaMTXConfig {
	return &MediaMTXConfig{
		streams: make([]StreamConfig, 0, MaxStreams),
	}
}

// AddStream adds a stream configuration. Returns error if max streams exceeded.
func (c *MediaMTXConfig) AddStream(cfg StreamConfig) error {
	if len(c.streams) >= MaxStreams {
		return fmt.Errorf("maximum streams (%d) exceeded", MaxStreams)
	}
	c.streams = append(c.streams, cfg)
	return nil
}

// RemoveStream removes a stream by ID. Returns false if not found.
func (c *MediaMTXConfig) RemoveStream(id string) bool {
	for i, s := range c.streams {
		if s.ID == id {
			c.streams = append(c.streams[:i], c.streams[i+1:]...)
			return true
		}
	}
	return false
}

// Streams returns a copy of all configured streams.
func (c *MediaMTXConfig) Streams() []StreamConfig {
	result := make([]StreamConfig, len(c.streams))
	copy(result, c.streams)
	return result
}

// StreamCount returns the number of configured streams.
func (c *MediaMTXConfig) StreamCount() int {
	return len(c.streams)
}

// GenerateYAML generates a MediaMTX-compatible YAML configuration.
//
// The generated configuration enforces:
//   - No recording (record: no)
//   - No transcoding (no runOnReady, no ffmpeg)
//   - Codec passthrough via RTSP source
//   - WebRTC enabled for low-latency output
//   - HLS enabled as fallback
//   - On-demand connections
//   - Source URL uses placeholder format for credential injection at runtime
//
// SECURITY: No actual camera credentials appear in this output.
// Credentials are resolved by the runtime credential manager from
// encrypted local configuration.
func (c *MediaMTXConfig) GenerateYAML() ([]byte, error) {
	var b strings.Builder

	// Global configuration header
	b.WriteString("# MediaMTX Configuration - Generated by SafeGAI Edge Gateway\n")
	b.WriteString("# WARNING: Do not manually edit. Regenerated on stream config change.\n")
	b.WriteString("# SECURITY: No camera credentials in this file.\n")
	b.WriteString("# Credentials are injected at runtime from encrypted local config.\n")
	b.WriteString("#\n")
	b.WriteString("# Performance budget: MediaMTX + 4 streams within 1GB memory\n")
	b.WriteString("# Codec: H.264 passthrough only (no transcoding)\n")
	b.WriteString("# Recording: disabled\n")
	b.WriteString("\n")

	// Global settings
	b.WriteString("# Global settings\n")
	b.WriteString("logLevel: info\n")
	b.WriteString("logDestinations: [stdout]\n")
	b.WriteString("\n")

	// API settings
	b.WriteString("# API for health monitoring\n")
	b.WriteString("api: yes\n")
	b.WriteString("apiAddress: 127.0.0.1:9997\n")
	b.WriteString("\n")

	// RTSP server settings (input)
	b.WriteString("# RTSP server (source input)\n")
	b.WriteString("rtsp: yes\n")
	b.WriteString("rtspAddress: :8554\n")
	b.WriteString("protocols: [tcp]\n")
	b.WriteString("\n")

	// WebRTC settings (preferred output)
	b.WriteString("# WebRTC output (preferred - low latency)\n")
	b.WriteString("webrtc: yes\n")
	b.WriteString("webrtcAddress: :8889\n")
	b.WriteString("\n")

	// HLS settings (fallback output)
	b.WriteString("# HLS output (fallback - wider compatibility)\n")
	b.WriteString("hls: yes\n")
	b.WriteString("hlsAddress: :8888\n")
	b.WriteString("hlsAlwaysRemux: no\n")
	b.WriteString("\n")

	// Explicitly disable recording
	b.WriteString("# Recording: DISABLED (no recording by design)\n")
	b.WriteString("record: no\n")
	b.WriteString("\n")

	// Stream paths
	b.WriteString("# Stream paths (max 4 simultaneous streams)\n")
	b.WriteString("paths:\n")

	if len(c.streams) == 0 {
		b.WriteString("  # No streams configured\n")
	}

	for _, stream := range c.streams {
		b.WriteString(fmt.Sprintf("  %s:\n", stream.ID))

		// Source configuration - placeholder URL
		// Actual credentials are injected at runtime by the credential manager.
		b.WriteString(fmt.Sprintf("    # Stream: %s\n", stream.Name))
		b.WriteString(fmt.Sprintf("    # Resolution: %dx%d, FPS: %d, Max bitrate: %d Kbps\n",
			stream.Resolution.Width, stream.Resolution.Height, stream.FPS, stream.MaxBitrateKbps))
		b.WriteString("    # Source URL injected at runtime from encrypted config\n")
		b.WriteString(fmt.Sprintf("    source: %s\n", stream.SourceURL))
		b.WriteString("    sourceProtocol: tcp\n")

		// On-demand setting
		if stream.OnDemand {
			b.WriteString("    sourceOnDemand: yes\n")
			b.WriteString("    sourceOnDemandStartTimeout: 10s\n")
			b.WriteString("    sourceOnDemandCloseAfter: 30s\n")
		} else {
			b.WriteString("    sourceOnDemand: no\n")
		}

		// Explicitly no recording per path
		b.WriteString("    record: no\n")

		// No runOnReady (no transcoding, no ffmpeg)
		b.WriteString("    # No runOnReady - codec passthrough only, no transcoding\n")

		b.WriteString("\n")
	}

	return []byte(b.String()), nil
}
