network:
  version: 2
  ethernets:
    camera_lan:
      match:
        macaddress: REPLACE_CAMERA_LAN_MAC
      set-name: camera0
      addresses:
        - 192.168.50.1/24
      dhcp4: false
    uplink_lan:
      match:
        macaddress: REPLACE_UPLINK_LAN_MAC
      set-name: uplink0
      dhcp4: true
      dhcp4-overrides:
        route-metric: 100
